use crate::error::CoreError;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;
use std::process::Command as StdCommand;
use std::time::Instant;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionResult {
    pub success: bool,
    pub exit_code: Option<i32>,
    pub stdout: String,
    pub stderr: String,
    pub output_payload: String,
    pub duration_ms: u64,
}

pub struct NodeRunner;

impl NodeRunner {
    /// Executes a node within a project root by feeding input and capturing output.
    pub fn execute_node(
        project_root: &Path,
        node_id: &str,
        _file_path: &str,
        entrypoint: Option<&str>,
        input: &str,
    ) -> Result<ExecutionResult, CoreError> {
        let start_time = Instant::now();
        let target_dir = project_root.join(".merm").join("target");

        // 1. Check if there is an exact entrypoint or function we can invoke via a generated harness
        let harness_dir = project_root.join("tests");
        if !harness_dir.exists() {
            let _ = fs::create_dir_all(&harness_dir);
        }

        let harness_file = harness_dir.join(format!("merm_exec_{}.rs", sanitize_ident(node_id)));
        let entry_fn = entrypoint.unwrap_or("run");

        // Detect crate name from Cargo.toml
        let crate_name = Self::detect_crate_name(project_root).unwrap_or_else(|| "app".to_string());

        // Generate temporary test harness
        let harness_code = format!(
            r#"// Auto-generated by merm executable node harness
#[test]
fn test_merm_node_execution() {{
    let input = std::env::var("MERM_INPUT").unwrap_or_default();
    println!("__MERM_OUTPUT_START__");
    
    // Attempt to invoke the node entrypoint
    // Case 1: Direct function or Struct::entry_fn
    #[allow(unused_imports)]
    use {}::*;

    let result = {{
        // Check if there is a module or struct named {}
        {}::{}(&input)
    }};

    println!("{{}}", result);
    println!("__MERM_OUTPUT_END__");
}}
"#,
            crate_name.replace('-', "_"),
            node_id,
            node_id,
            entry_fn
        );

        let created_harness = fs::write(&harness_file, harness_code).is_ok();

        // Run cargo test on the harness
        let mut cmd = StdCommand::new("cargo");
        cmd.current_dir(project_root)
            .env("CARGO_TARGET_DIR", &target_dir)
            .env("MERM_INPUT", input)
            .arg("test")
            .arg("--test")
            .arg(format!("merm_exec_{}", sanitize_ident(node_id)))
            .arg("--")
            .arg("--nocapture");

        let output_res = cmd.output();

        // Clean up the temporary harness file
        if created_harness && harness_file.exists() {
            let _ = fs::remove_file(&harness_file);
        }

        let duration_ms = start_time.elapsed().as_millis() as u64;

        match output_res {
            Ok(out) => {
                let stdout = String::from_utf8_lossy(&out.stdout).to_string();
                let stderr = String::from_utf8_lossy(&out.stderr).to_string();
                let success = out.status.success();

                let output_payload = if let Some(start_idx) = stdout.find("__MERM_OUTPUT_START__") {
                    let after_start = &stdout[start_idx + "__MERM_OUTPUT_START__".len()..];
                    if let Some(end_idx) = after_start.find("__MERM_OUTPUT_END__") {
                        after_start[..end_idx].trim().to_string()
                    } else {
                        after_start.trim().to_string()
                    }
                } else if success {
                    format!("Executed {} successfully. Output: [Ok]", node_id)
                } else {
                    format!(
                        "Execution failed (Exit code: {:?})\n{}",
                        out.status.code(),
                        stderr
                    )
                };

                Ok(ExecutionResult {
                    success,
                    exit_code: out.status.code(),
                    stdout,
                    stderr,
                    output_payload,
                    duration_ms,
                })
            }
            Err(e) => {
                // Fallback to testing directly with cargo test <node_id>
                let fallback_start = Instant::now();
                let mut fallback_cmd = StdCommand::new("cargo");
                fallback_cmd
                    .current_dir(project_root)
                    .env("CARGO_TARGET_DIR", &target_dir)
                    .env("MERM_INPUT", input)
                    .arg("test")
                    .arg(node_id)
                    .arg("--")
                    .arg("--nocapture");

                if let Ok(f_out) = fallback_cmd.output() {
                    let stdout = String::from_utf8_lossy(&f_out.stdout).to_string();
                    let stderr = String::from_utf8_lossy(&f_out.stderr).to_string();
                    let success = f_out.status.success();
                    Ok(ExecutionResult {
                        success,
                        exit_code: f_out.status.code(),
                        stdout: stdout.clone(),
                        stderr,
                        output_payload: stdout,
                        duration_ms: fallback_start.elapsed().as_millis() as u64,
                    })
                } else {
                    Err(CoreError::LayoutFailed(format!(
                        "Failed to execute cargo runner for node {}: {}",
                        node_id, e
                    )))
                }
            }
        }
    }

    fn detect_crate_name(project_root: &Path) -> Option<String> {
        let cargo_toml = project_root.join("Cargo.toml");
        if let Ok(content) = fs::read_to_string(cargo_toml) {
            for line in content.lines() {
                let t = line.trim();
                if t.starts_with("name =") {
                    let parts: Vec<&str> = t.split('=').collect();
                    if parts.len() >= 2 {
                        let name = parts[1].trim().trim_matches('"').trim_matches('\'');
                        return Some(name.to_string());
                    }
                }
            }
        }
        None
    }
}

fn sanitize_ident(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sanitize_ident() {
        assert_eq!(sanitize_ident("AuthService"), "authservice");
        assert_eq!(sanitize_ident("Order-Processor"), "order_processor");
    }
}
