[package]
name = "merm-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
merm-core = { path = "../merm-core" }
merm-render = { path = "../merm-render" }
merm-ipc = { path = "../merm-ipc" }
serde.workspace = true
thiserror.workspace = true
log.workspace = true
winit = "0.30"
softbuffer = "0.4"
tokio.workspace = true
notify.workspace = true
arboard = "3.6.1"
